#Define dictionary of LAMMPS unit styles
unit_style = {}
    
unit_style['lj'] = {    "mass":             None,
                        "distance":         None,
                        "time":             None,
                        "energy":           None,
                        "velocity":         None,
                        "force":            None,
                        "torque":           None,
                        "temperature":      None,
                        "pressure":         None,
                        "dynamic viscosity":None,
                        "charge":           None,
                        "dipole":           None,
                        "electric field":   None,
                        "density":          None}
                  
unit_style['real'] = {  "mass":             "g/mol", 
                        "distance":         "angstrom", 
                        "time":             "fs", 
                        "energy":           "kcal/mol", 
                        "velocity":         "angstrom/fs", 
                        "force":            "kcal/(mol*angstrom)",
                        "torque":           "kcal/mol",
                        "temperature":      "K",
                        "pressure":         "atm",
                        "dynamic viscosity":"Pa*s/10",
                        "charge":           "e",
                        "dipole":           "e*angstrom",
                        "electric field":   "V/angstrom",
                        "density":          "g/cm^3"}

unit_style['metal'] = { "mass":             "g/mol", 
                        "distance":         "angstrom", 
                        "time":             "ps", 
                        "energy":           "eV", 
                        "velocity":         "angstrom/ps", 
                        "force":            "eV/angstrom",
                        "torque":           "eV",
                        "temperature":      "K",
                        "pressure":         "bar",
                        "dynamic viscosity":"Pa*s/10",
                        "charge":           "e",
                        "dipole":           "e*angstrom",
                        "electric field":   "V/angstrom",
                        "density":          "g/cm^3"}

unit_style['si'] = {    "mass":             "kg",
                        "distance":         "m",
                        "time":             "s",
                        "energy":           "J",
                        "velocity":         "m/s",
                        "force":            "N",
                        "torque":           "N*m",
                        "temperature":      "K",
                        "pressure":         "Pa",
                        "dynamic viscosity":"Pa*s",
                        "charge":           "C",
                        "dipole":           "C*m",
                        "electric field":   "V/m",
                        "density":          "kg/m^3"}

unit_style['cgs'] = {   "mass":             "g",
                        "distance":         "cm",
                        "time":             "s",
                        "energy":           "erg",
                        "velocity":         "cm/s",
                        "force":            "dyn",
                        "torque":           "dyn*cm",
                        "temperature":      "K",
                        "pressure":         "0.1*Pa",
                        "dynamic viscosity":"Pa*s/10",
                        "charge":           "10*c0*C",
                        "dipole":           "10*c0*C*cm",
                        "electric field":   "c0*uV/cm",
                        "density":          "g/cm^3"}

unit_style['electron']={"mass":             "amu",
                        "distance":         "aBohr",
                        "time":             "fs",
                        "energy":           "2*Ry",
                        "velocity":         "2*Ry*aBohr/hbar",
                        "force":            "2*Ry/aBohr",
                        "torque":           "dyn*cm",
                        "temperature":      "K",
                        "pressure":         "Pa",
                        "charge":           "e",
                        "dipole":           "1e-21/c0*C*m",
                        "electric field":   "V/cm"}
                        
unit_style['micro'] = { "mass":             "pg",
                        "distance":         "um",
                        "time":             "us",
                        "energy":           "pg*um^2/us^2",
                        "velocity":         "um/us",
                        "force":            "pg*um/us^2",
                        "torque":           "pg*um^2/us^2",
                        "temperature":      "K",
                        "pressure":         "pg/(um*us^2)",
                        "dynamic viscosity":"pg/(um*us)",
                        "charge":           "1e-12*C",
                        "dipole":           "1e-12*C*um",
                        "electric field":   "V/um",
                        "density":          "pg/um^3"}

unit_style['nano'] = {  "mass":             "1e-18*g",
                        "distance":         "nm",
                        "time":             "ns",
                        "energy":           "1e-18*g*nm^2/ns^2",
                        "velocity":         "nm/ns",
                        "force":            "1e-18*g*nm/ns^2",
                        "torque":           "1e-18*g*nm^2/ns^2",
                        "temperature":      "K",
                        "pressure":         "1e-18*g/(nm*ns^2)",
                        "dynamic viscosity":"1e-18*g/(nm*ns)",
                        "charge":           "e",
                        "dipole":           "e*nm",
                        "electric field":   "V/nm",
                        "density":          "1e-18*g/nm^3"}   